[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.3"
clap = { version = "4.5.21", features = ["derive"] }
regex = "1.11.1"
itertools = "0.13.0"
